name: 'MSIX Bundler'
description: 'This action creates an msixbundle file from a list of MSIX packages'
author: 'Lance McCarthy'
branding:
  icon: 'box'
  color: 'purple'
inputs:
  msix-folder:
    description: 'The absolute path to the folder containing all the MSIX files to be bundled.'
    required: true
    default: ''
  msixbundle-filepath:
    description: 'The absolute file path to be used for the .msixbundle (C:\MyFolder\MyApp_1.0.0.0_x86_x64.msixbundle).'
    required: true
    default: ''
  msixbundle-version:
    description: 'Specifies the version number of the bundle. The version number MUST be in four parts separated by periods in the form: <Major>.<Minor>.<Build>.<Revision>.'
    required: true
    default: '0.0.0.0'
  sdk-version:
    description: 'The version of makeappx.exe and signtool.exe (default is 10.0.19041.0).'
    required: false
    default: '10.0.19041.0'
  architecture:
    description: 'The architecture version of makeappx.exe to use (default is x86).'
    required: false
    default: 'x86'
  enable-bundle-signing:
    description: 'Enables signing the bundle using signtool.exe'
    required: false
    default: false
  certificate-path:
    description: 'Path to the code signing certificate (i.e., the PFX file).'
    default: ''
  certificate-private-key:
    description: 'The private key (password) for the PFX.'
    required: false
    default: ''
  signing-hash-algorithm:
    description: 'The hash algorithm used for signing (default is SHA256).'
    required: false
    default: 'SHA256'
outputs:
  msixbundle_path:
    description: "The absolute file path to the generated msixbundle file."
    value: ${{ steps.bundle.outputs.final_path }}
runs:
  using: "composite"
  steps:
    - id: bundle
      shell: pwsh
      run: |
        ## ********************************** ##
        ## ******** STEP 1. BUNDLE ********** ##
        ## ********************************** ##
        echo "Setting correct SDK tools folder (added to PATH)"
        $sdkToolsPath = Join-Path -Path "C:\Program Files (x86)\Windows Kits\10\bin" -ChildPath ${{ inputs.sdk-version }} -AdditionalChildPath ${{ inputs.architecture }}
        $env:Path += ";$sdkToolsPath"

        $msixesFolder = "${{ inputs.msix-folder }}"
        $msixBundleFilePath = "${{ inputs.msixbundle-filepath }}"
        $msixbundleVersion = "${{ inputs.msixbundle-version }}"

        echo "Input folder (contains only MSIX files) -> $msixesFolder"
        echo "Desired File name for msixbundle -> $msixBundleFilePath"
        echo "Desired Version for msixbundle -> $msixbundleVersion"

        echo "Creating bundle with MakeAppx..."
        MakeAppx.exe bundle /bv $msixbundleVersion /d $msixesFolder /p $msixBundleFilePath

        # MakeAppx.exe Docs and Reference 
        # https://docs.microsoft.com/en-us/windows/msix/package/create-app-package-with-makeappx-tool
        # https://docs.microsoft.com/en-us/windows/msix/packaging-tool/bundle-msix-packages#step-2-bundle-the-packages

        ## ************************************ ##
        ## ********** STEP 2. SIGN ************ ##
        ## ************************************ ##

        # check if the user wants to sign the bundle
        if (${{ inputs.enable-bundle-signing }}){
          echo "Beginning code signing of msixbundle file."

          $hashAlgo = ${{ inputs.signing-hash-algorithm }}
          $certPath = ${{ inputs.certificate-path }}
          $certKey = ${{ inputs.certificate-private-key }}
          
          $isCertPathValid = Test-Path -Path $certPath
          if($isCertPathValid -eq $false){
            Write-Error "You must have a valid path value for the signing certificate."
            exit 1
          }
          
          if([string]::IsNullOrWhiteSpace($certKey)){
            Write-Error "You must have a password for the PFX certificate."
            exit 1
          }

          $currentDirectory = Get-Location
          $msixBundlePath = Join-Path -Path $currentDirectory -ChildPath $msixBundleFilePath

          try {
            echo "Parameters validated, beginning signing..."

            SignTool.exe sign /fd $hashAlgo /a /f $certPath /p $certKey $msixBundlePath

            # Reference Docs
            # https://docs.microsoft.com/en-us/windows/msix/packaging-tool/bundle-msix-packages#step-3-sign-the-bundle
          }
          catch { 
              echo "An error occurred:"
              echo $_.ScriptStackTrace
              exit 1
          }

          echo "Signing complete!"
        } else {
          echo "Bundle signing is not enabled, skipping signing."
        }

        if([string]::IsNullOrWhiteSpace($msixBundlePath)){
          echo "The output file path is empty, something went wrong. Please check the build log output for details."
          exit 1
        }

        # Set the output variable
        echo "::set-output name=final_path::$msixBundlePath"
